schema:
  - https://itjoljzfpzfehyxrmxhb.supabase.co/graphql/v1:
      headers:
        apiKey:
          eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0am9sanpmcHpmZWh5eHJteGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMjI2MDIsImV4cCI6MjA1Mzg5ODYwMn0.zV0c8IqVNX5qMfcumihmMq-Ptll5Vo_RsxADplqqYvg
documents: '**/*.graphql'
